---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-elasticsearch-k8s-metrics-adapter
  description: Buildkite Pipeline for elasticsearch-k8s-metrics-adapter
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/elasticsearch-k8s-metrics-adapter

spec:
  type: buildkite-pipeline
  owner: group:cloud-k8s-operator
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-k8s-metrics-adapter
    spec:
      repository: elastic/elasticsearch-k8s-metrics-adapter
      pipeline_file: ".buildkite/pipeline.yml"
      provider_settings:
        build_branches: true
        build_pull_request_ready_for_review: true
        build_tags: true
        publish_blocked_as_pending: true
        publish_commit_status: true
        publish_commit_status_per_step: false
        skip_pull_request_builds_for_existing_commits: false
      teams:
        cloud-k8s-region:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY

# Declare quality gates pipeline
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: elasticsearch-k8s-metrics-adapter-tests-pipeline
  description: Definition of the lelasticsearch-k8s-metrics-adapter-tests pipeline
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/elasticsearch-k8s-metrics-adapter-tests
spec:
  type: buildkite-pipeline
  owner: group:cloud-k8s-operator
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elasticsearch-k8s-metrics-adapter-tests
      description: Pipeline that tests the service integration in various environments
    spec:
      repository: elastic/elasticsearch-k8s-metrics-adapter
      pipeline_file: ./.buildkite/pipeline.elasticsearch-k8s-metrics-adapter-tests.yaml
      provider_settings:
        trigger_mode: none
      teams:
        cloud-k8s-region:
          access_level: MANAGE_BUILD_AND_READ
        cloud-tooling:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY