apiVersion: v1
data:
  config.yml: |
    {{- .Values.config | toYaml | trim  | nindent 4 }}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: elasticsearch-metrics-apiserver
  name: elasticsearch-custom-metrics-config-{{ include "yamlHash" .Values.config  }}
  namespace: {{ .Release.Namespace }}