{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  {{- with .Values.namespace.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.namespace.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Release.Namespace }}
{{- end }}
