apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-metrics-apiserver
  labels:
    {{- include "elasticsearch-metrics-apiserver.combinedLabels" . | nindent 4 }}
spec:
  ports:
    - name: https
      port: 443
      targetPort: 6443
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: elasticsearch-metrics-apiserver