# These pipeline steps constitute the quality gate for your service within the production environment.
# Incorporate any necessary additional logic to validate the service's integrity. A failure in
# this pipeline build will prevent further progression to the subsequent stage.

steps:
  - command:
    - echo "Waiting for 10m for indicative health metrics"
    - sleep 600
  - wait

  - label: ":rocket: Run observability gates"
    if: build.env("ENVIRONMENT") == "production-canary"
    trigger: "serverless-quality-gates"
    build:
      branch: main
      commit: HEAD
      message: "${BUILDKITE_MESSAGE}"
      env:
        TARGET_ENV: ${ENVIRONMENT}
        SERVICE: elasticsearch-metrics-apiserver
        CONTAINER_NAME: elasticsearch-metrics-apiserver
        CHECK_CONTAINER_RESTART_COUNT: true
        CHECK_METRICS_COUNT: true
