metricSets:
  - indices: [ 'metricbeat-*' ]
    fields:
      - patterns: [ '^prometheus\.metrics\.' ]
        labels: [ '^prometheus\.labels\.(.*)' ]
      - name: "kibana.stats.load.pod" # Kibana load per Pod
        search: # Custom search
          metricPath: ".aggregations.custom_name.buckets.[0].pod_load.value"
          timestampPath: ".aggregations.custom_name.buckets.[0].timestamp.value_as_string"
          body: >
            {
              "query": {
                "bool": {
                  "must": [
                    {
                      "match": {
                        "kibana.stats.name": "{{ index .PodSelectors "kibana.k8s.elastic.co/name" }}"
                      }
                    },
                    {
                      "match": {
                        "kubernetes.namespace": "{{ .Namespace }}"
                      }
                    }
                  ],
                  "filter": [
                    {
                      "exists": {
                        "field": "kibana.stats.load"
                      }
                    },
                    {
                      "range": {
                        "@timestamp": {
                          "gte": "now-2m"
                        }
                      }
                    }
                  ]
                }
              },
              "size": 0,
              "aggs": {
                "custom_name": {
                  "terms": {
                    "field": "kibana.stats.name"
                  },
                  "aggs": {
                    "pods_count": {
                      "cardinality": {
                        "field": "kubernetes.pod.name"
                      }
                    },
                    "maxLoad": {
                      "max": {
                        "field": "kibana.stats.load"
                      }
                    },
                    "timestamp": {
                      "max": {
                        "field": "@timestamp"
                      }
                    },
                    "pod_load": {
                      "bucket_script": {
                        "buckets_path": {
                          "load": "maxLoad"
                        },
                        "script": "params.load / {{ len .Objects }}"
                      }
                    }
                  }
                }
              }
            }
      - patterns: [ '^kibana\.stats\.' ]
#        resources:
#          - service.name:
#              resource: "kibana"
#          - kubernetes.pod.name:
#              resource: "pod"